services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Bitmotion\Mautic\:
    resource: '../Classes/*'

  Bitmotion\Mautic\Hooks\MauticFormHook:
    public: true

#  Bitmotion\Mautic\EventListener\SynchronizeMauticData:
#    tags:
#      - name: event.listener
#        identifier: synchronizeMauticData
#        event: TYPO3\CMS\Backend\Controller\Event\AfterFormEnginePageInitializedEvent
